from django.urls import path

from apps.domains.api import (
    TenantDomainDNSCheckView,
    TenantDomainDetailView,
    TenantDomainListCreateView,
    TenantDomainProvisionView,
    TenantDomainVerifyView,
)
from apps.domains.lifecycle_api import (
    TenantDomainEmergencyReactivateView,
    TenantDomainEmergencySuspendView,
)
from apps.mailboxes.api import (
    TenantForwarderDetailView,
    TenantForwarderListCreateView,
    TenantMailboxDetailView,
    TenantMailboxListCreateView,
    TenantMailboxPasswordResetView,
    TenantMailboxReactivateView,
    TenantMailboxSuspendView,
)
from apps.tenants.api import (
    TenantDetailView,
    TenantInvitationDetailView,
    TenantInvitationListCreateView,
    TenantListCreateView,
    TenantMemberDetailView,
    TenantMemberListView,
)
from apps.tenants.lifecycle_api import TenantEmergencyReactivateView, TenantEmergencySuspendView


urlpatterns = [
    path("tenants/", TenantListCreateView.as_view(), name="tenant-list-create"),
    path("tenants/<slug:slug>/", TenantDetailView.as_view(), name="tenant-detail"),
    path(
        "tenants/<slug:tenant_slug>/suspend/",
        TenantEmergencySuspendView.as_view(),
        name="tenant-emergency-suspend",
    ),
    path(
        "tenants/<slug:tenant_slug>/reactivate/",
        TenantEmergencyReactivateView.as_view(),
        name="tenant-emergency-reactivate",
    ),
    path(
        "tenants/<slug:tenant_slug>/members/",
        TenantMemberListView.as_view(),
        name="tenant-member-list",
    ),
    path(
        "tenants/<slug:tenant_slug>/members/<int:pk>/",
        TenantMemberDetailView.as_view(),
        name="tenant-member-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/invitations/",
        TenantInvitationListCreateView.as_view(),
        name="tenant-invitation-list-create",
    ),
    path(
        "tenants/<slug:tenant_slug>/invitations/<int:pk>/",
        TenantInvitationDetailView.as_view(),
        name="tenant-invitation-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/",
        TenantDomainListCreateView.as_view(),
        name="tenant-domain-list-create",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:pk>/",
        TenantDomainDetailView.as_view(),
        name="tenant-domain-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:pk>/suspend/",
        TenantDomainEmergencySuspendView.as_view(),
        name="tenant-domain-emergency-suspend",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:pk>/reactivate/",
        TenantDomainEmergencyReactivateView.as_view(),
        name="tenant-domain-emergency-reactivate",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:pk>/verify/",
        TenantDomainVerifyView.as_view(),
        name="tenant-domain-verify",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:pk>/provision/",
        TenantDomainProvisionView.as_view(),
        name="tenant-domain-provision",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:pk>/dns-check/",
        TenantDomainDNSCheckView.as_view(),
        name="tenant-domain-dns-check",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/mailboxes/",
        TenantMailboxListCreateView.as_view(),
        name="tenant-mailbox-list-create",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/mailboxes/<int:pk>/",
        TenantMailboxDetailView.as_view(),
        name="tenant-mailbox-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/mailboxes/<int:pk>/suspend/",
        TenantMailboxSuspendView.as_view(),
        name="tenant-mailbox-suspend",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/mailboxes/<int:pk>/reactivate/",
        TenantMailboxReactivateView.as_view(),
        name="tenant-mailbox-reactivate",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/mailboxes/<int:pk>/password-reset/",
        TenantMailboxPasswordResetView.as_view(),
        name="tenant-mailbox-password-reset",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/forwarders/",
        TenantForwarderListCreateView.as_view(),
        name="tenant-forwarder-list-create",
    ),
    path(
        "tenants/<slug:tenant_slug>/domains/<int:domain_pk>/forwarders/<int:pk>/",
        TenantForwarderDetailView.as_view(),
        name="tenant-forwarder-detail",
    ),
]
